### PR TITLE
Check if texput.log exists (fix #21)

### LINKED ISSUE #21: Error: ENOENT: no such file or directory
Hello,
I'm getting this error:
```
events.js:173
      throw er; // Unhandled 'error' event
Error: ENOENT: no such file or directory, open 'C:\Users\username\AppData\Local\Temp\node-latex11943-4516-s5hath.2iall\texput.log'
```

Here is my code:

Latex string is passed as body param.
```js
'use strict';
const latex = require('node-latex');
const fs = require('fs');
const path = require('path');
module.exports = {
  pdf: ({ request, response }) => {
    const output = fs.createWriteStream(path.resolve('public', 'cv.pdf'));
    const options = {
      inputs: [
        path.resolve('assets', 'latex', 'inputs'),
        path.resolve('assets', 'latex', 'images'),
      ],
      fonts: path.resolve('assets', 'latex', 'fonts', 'itcavantgardestd'),
      cmd: 'xetex',
      errorLogs: path.resolve('public')
    };
    const pdf = latex(request.body.latex, options)
    pdf.pipe(output);
    pdf.on('error', error => {
      console.log(error);
    });
    pdf.on('finish', () => console.log(pdf));
    return null;
  }
};
```

Any idea why I'm getting this unhandled error ?

### PR DESCRIPTION
**Pull request by quantumsheep**
Fix #21 by checking if `texput.log` exists before opening it as a read stream.

### CODE REVIEW

**Comment by saadq** [comment]
Thanks for the PR @quantumsheep ! I'll verify this change this weekend and have it merged. I'll then publish a new version with your fix :)

**Comment by quantumsheep** [comment]
Hello! Waiting for the PR to be merged 😄

**Comment by saadq** [comment]
So sorry for my delay :(

I need to stop making promises on dates and then not meeting them... with that said I will definitely get to this tomorrow, I've added some alarms/reminders to make sure I do lol. Thanks for your patience @quantumsheep

**Comment by quantumsheep** [comment]
Don't worry, it's not that much of an urge and you don't owe me anything! Take your time, delays doesn't matter :)

File: index.js [hunk 1]
```diff
@@ -32,34 +32,42 @@ function latex(src, options) {
...
     const errorLogPath = path.join(tempPath, 'texput.log')
-    const errorLogStream = fs.createReadStream(errorLogPath)
 
-    if (userLogPath) {
-      const userLogStream = fs.createWriteStream(path.resolve(userLogPath))
-      errorLogStream.pipe(userLogStream)
-    }
+    fs.stat(errorLogPath, (err, stats) => {
+      if (err || !stats.isFile()) {
+        outputStream.emit('error', new Error('LaTeX Syntax Error'))
```
Comment (saadq) [inline index.js]: nit: Can you change error message to be something more along the lines of the error log file not existing?

**Review by saadq — CHANGES_REQUESTED** [review]
Looks good overall! If you could just change the error message a bit, should be ready for merging/publishing asap.

File: index.js (hunk 1 above)
Comment (quantumsheep) [reply index.js]: Like using `err` variable?

Comment (saadq) [reply index.js]: sorry, i meant instead of `LateX Syntax Error` it should be a different message like `No error log file` or something

Comment (quantumsheep) [reply index.js]: Here you go! `No error log file` was perfect.

**Comment by saadq** [comment]
Thanks very much for the fix @quantumsheep! I will publish a new version once I get home :)

**Comment by quantumsheep** [comment]
Thanks you :)

**Comment by saadq** [comment]
`v2.6.3` is out now. Thanks again @quantumsheep
